### ISSUE TITLE
Failing to compile on ios and android after update to 0.2

### ISSUE THREAD

**Issue by dignifiedquire** [svartalf/hostname#9]
Details: 

- error on ios: you can convert an usize to i32 - https://gist.github.com/r10s/56dfccebbc2d65b52e774ccde933bd5a
- error on android: undefined reference to sethostname - https://gist.github.com/r10s/3c620bddc01d8640e62287b966b10f93

worked fine with `0.1. 5`

**Comment by r10s** [comment]
maybe i did sth. wrong ianar (i am not a rust-expert  :) if some additional information are needed, please just ping me :)

**Comment by svartalf** [comment]
Thanks for a bug report! It was not really clarified what targets are supported for `0.1` version, apparently, this information was lost during the ownership transfer, sorry about that.

`arm-linux-androideabi` and `aarch64-linux-android` Android targets are already tested in CI and I dropped few iOS targets too (`armv7-apple-ios` and `x86_64-apple-ios`), so far everything [compiles correctly](https://github.com/svartalf/hostname/commit/1ad8f1ed1a0d1e5127fd564aa0e72dfc96e88c18/checks?check_suite_id=350668909), so it would be really helpful to provide a bit more information about your environments.

From what I understand, Android build targets Android 4.3 Jelly Bean (API 18) on a `armv7-linux-androideabi` platform?
It is also a bit unclear how exactly it compiles for iOS target, could you maybe provide executed command or smth, so I'll try to reproduce the issues.

**Comment by r10s** [comment]
hi @svartalf thanks for your help!

on android we use `armv7-linux-androideabi`, `aarch64-linux-android`, `i686-linux-android`, `x86_64-linux-android using` the most recent ndk. \_\_ANDROID_API\_\_ is set to 18 for 32bit and to 21 for 64bit. **rust compiling succeeds**, however, at the end **linking fails**, ndk-make complains about that sethostname is not there, see https://gist.github.com/r10s/3c620bddc01d8640e62287b966b10f93 (the first warning is not releated), with hostname 0.1.5, there is no problem.

on ios, **rust compiling fails** with the error shown above, the used targets are  ´aarch64-apple-ios´ and ´x86_64-apple-ios´ - at least this is what xcode claims.

**Comment by svartalf** [comment]
Yes, `hostname::set`, which is utilizes `sethostname` for *nix systems was introduced in `0.2.0`, that's why linking fails in your case.
It is still unclear to me, why CI builds are green, but at least we have a starting point for investigation now.

**Comment by svartalf** [comment]
Alright, here goes the follow-up:

For iOS we could extend the following check to include the ios targets also: https://github.com/svartalf/hostname/blob/b7b4faeee5de0fa8e3e3542c5029713f2175b415/src/nix.rs#L42-L46,
same as `nix` crate [does](https://github.com/nix-rust/nix/blob/12828154c0f229f7e03a88775852ffdb5851f94b/src/unistd.rs#L883-L892), that should handle the issue.

As for Android, I see that `sethostname`function was introduced in Android API 23 (see [NDK sources](https://android.googlesource.com/platform/prebuilts/ndk/+/dev/platform/sysroot/usr/include/unistd.h#319)), and it is probably the reason why linking fails.
Not sure how to handle that exactly, though: dynamic function loading seems rather complicated in that case, I would probably go with some sort of `set` feature, which will enable the `hostname::set` function.

@r10s, any thoughts about it?

**Comment by svartalf** [comment]
Okay, ce41122c6fd421b3f87ed66eb6c5c0e355bb3c1d should handle the iOS issue and 72fc33faf7aca32043efebad4d33d9b4bcc478a6 hides `hostname::set` function under a `#[cfg(feature = "set")]` feature (disabled by default), so it should handle any linking problems.

@dignifiedquire @r10s can you test it? Following patch section in the Cargo manifest should properly override the dependency:

```toml
[patch.crates-io]
hostname = { git = "https://github.com/svartalf/hostname.git", branch = "ios" }
```

**Comment by r10s** [comment]
@svartalf thanks, that looks good! and incredibly quick, thanks a lot. unfortunately, my rust-cargo-skills are not sufficient to try this out easily, the hostname dependency is not used directly by deltachat.

i tried putting the patch to all Cargo.tomls i could find, but for some reasons xcode did not picked it up. maybe we do a pr on deltachat that reverts the change to 0.1.5 we've just done for now to get things out.

**Comment by dignifiedquire** [comment]
Compiled it successfully for ios (I don't have android setup)

**Comment by r10s** [comment]
@dignifiedquire thanks a lot for testing!

**Comment by svartalf** [comment]
Quick follow-up: how does the testing going on? Had you any chance to test it both for iOS and Android?

**Comment by svartalf** [comment]
So, I hide the `hostname::set` function with a feature gate; as it was a bit of a rush to publish it as a default part of `v0.2.0` and I tried to test the Android/iOS compatibility locally as much as I can, it should be okay now.

@hpk42, @dignifiedquire, can we test your case once again with the `hostname = "0.3"` version?

**Comment by r10s** [comment]
sorry, i did not came back to this sooner. not sure if we're back on the hostname-origin-crate, however. but if so, we will see if things work :) thanks a lot for helping :)
